spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: cndgus97
    driver-class-name: org.mariadb.jdbc.Driver
  
  devtools:
    livereload:
      enabled: true
  
  freemarker:
    cache: false 
  
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
       
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
   
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    root: INFO
    org:
      hibernate:  
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  file:
    path: logs
              
---
spring:
  profiles: dev
logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "/logs/abc.%d{yyyy-MM-dd}.%i"
  file:
    name: /logs/abc.log
    max-history: 30
  level:
    org:
      springframework: INFO
        