spring:
  datasource:
    url: ENC(L/QQMCQXCwG+FUtoyzpD67L97za9hODUpbqZaK+WDNooF0PTMWh1loAiSAurWm4K3svCQSPF2f+AveO7hgpmhfZgdhoqFWkUSU1Gk6pr5Ao7ArfG5PPTTQ==)
    username: ENC(sTs67NhfVVWKPQxy+EafLQ==)
    password: ENC(aUG1Tnf7Mk8GTxgzX43EAlBVQn7U+R8A)
    driver-class-name: org.mariadb.jdbc.Driver
  
  devtools:
    livereload:
      enabled: true
  
  freemarker:
    cache: false 
  
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
       
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
   
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    root: INFO
    org:
      hibernate:  
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  file:
    path: logs
    
jasypt:
  encryptor:
    bean: jasyptStringEncryptor          
jwt:
  header: Authorization
  secret: ENC(7VmCyb0XZtqSidRG2No/SBETuIAtlxUXVDJnxZcEIcvmePOhzBe08niDgcGGoGNNTrrkdOYqBQnRoj3c1LiFSWAvku3K336t)
  token-validity-in-seconds: 86400
---
spring:
  profiles: dev
logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "/logs/abc.%d{yyyy-MM-dd}.%i"
  file:
    name: /logs/abc.log
    max-history: 30
  level:
    org:
      springframework: INFO
        